- name: Setup Frontend
  hosts: all
  become: yes
  roles:
    - frontend






## ansible-playbook -i frontend-dev.devopsblessed.store, frontend.yml -e ansible_user=centos -e ansible_password=DevOps321
## ansible-playbook  -i frontend-dev.devopsblessed.store, roboshop.yml -e role_name=frontend -e ansible_user=centos -e ansible_password=DevOps321


