- name: Setup Frontend
  hosts: all
  become: yes
  roles:
    - frontend






##[ centos@workstation ~/roboshop-ansible ]$ ansible-playbook -i frontend-dev.devopsblessed.store, frontend.yml -e ansible_user=centos -e ansible_password=DevOps321
