- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory


- name: Download and Extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes




###Learning Notes##

## Here we will look for ansible module on how to do the below task in ansible

#  app_presetup(){
#    echo -e "${color} Add Application User ${nocolor}"
#    id roboshop &>>$log_file
#    if [ $? -eq 1 ]; then
#    useradd roboshop &>>$log_file
#    fi
#
#    stat_check $?
#
#    echo -e "${color} Create Application Directory ${nocolor}"
#    rm -rf ${app_path} &>>$log_file
#    mkdir ${app_path}
#
#    stat_check $?
#
#    echo -e "${color} Download Application Content ${nocolor}"
#    curl -o /tmp/$component.zip https://roboshop-artifacts.s3.amazonaws.com/$component.zip &>>$log_file
#    cd ${app_path}
#
#    stat_check $?
#
#    echo -e "${color} Extract Application content ${nocolor}"
#    cd ${app_path}
#    unzip /tmp/$component.zip &>>$log_file
#
#    stat_check $?






# syntax to add a user roboshop module

#- name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
#  ansible.builtin.user:
#    name: james
#    shell: /bin/bash
#    groups: admins,developers
#    append: yes

## syntax to remove a directory and add a directoy
#- name: Remove file (delete file)
#  ansible.builtin.file:
#    path: /etc/foo.txt
#    state: absent


##syntax to create directory
#- name: Create a directory if it does not exist
#  ansible.builtin.file:
#    path: /etc/some_directory
#    state: directory
#    mode: '0755'
