

#echo -e "${color} Download Application Content ${nocolor}"
#curl -o /tmp/$component.zip https://roboshop-artifacts.s3.amazonaws.com/$component.zip &>>$log_file
#cd ${app_path}
#
#stat_check $?
#
#echo -e "${color} Extract Application content ${nocolor}"
#cd ${app_path}
#unzip /tmp/$component.zip &>>$log_file
#stat_check $?

- name: Add Application User
  ansible.builtin.user:
      name: roboshop

- name: Remove old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory