
- name: Copy Mongodb.repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongodb Client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name:  Load Schema
  ansible.builtin.schema: mongo --host mongodb-dev.devopsblessed.store </app/schema/{{ component }}.js




#echo -e "${color} Copy Mongodb.repo ${nocolor}"
#cp /home/centos/roboshop-shell/mongodb.repo /etc/yum.repos.d/mongo.repo &>>$log_file
#stat_check $?
#
#echo -e "${color}Install Mongodb Client ${nocolor}"
#yum install mongodb-org-shell -y &>>$log_file
#stat_check $?
#
#echo -e "${color} Load Schema ${nocolor}"
#mongo --host mongodb-dev.devopsblessed.store <${app_path}/schema/${component}.js &>>$log_file
#stat_check $?
