- name: Install MySQL Client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.devopsblessed.store -uroot -pRoboShop@1 < /app/schema/{{ component }}.sql








#
#
#  mysql_schema_setup(){
#
#  echo -e "${color} Install Mysql Client ${nocolor}"
#  yum install mysql -y &>>$log_file
#  stat_check $?
#
#  echo -e "${color} Load Schema ${nocolor}"
#  mysql -h mysql-dev.devopsblessed.store -uroot -p${mysql_root_password} < /app/schema/${component}.sql &>>$log_file
#  stat_check $?
#}