- name: Configuring NodeJS Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: app_presetup.yml


- name: Load NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: SystemD Setup`
  ansible.builtin.import_tasks:
    file: systemd_setup.yml


#Syntax for load nodejs
#- - name: Change the working directory to somedir/ before executing the command
#    ansible.builtin.shell: somescript.sh >> somelog.txt
#    args:
#      chdir: somedir/

# here we used curly braces in the variable component because there is a value in front of the variable
## in the app that uses the nodejs we will declare a variable as component


#  nodejs() {
#  echo -e "${color} Configuring NodeJS Repos ${nocolor}"
#  curl -sL https://rpm.nodesource.com/setup_lts.x | bash &>>$log_file
#  stat_check $?
#
#  echo -e "${color} install NodeJS ${nocolor}"
#  yum install nodejs -y &>>$log_file
#  stat_check $?
#
#  app_presetup
#
#  echo -e "${color} Install NodeJS Dependencies ${nocolor}"
#  npm install &>>$log_file
#  stat_check $?
#
#  systemd_setup
#
#}



#syntax to import task
#- name: Include task list in play
#      ansible.builtin.import_tasks:
#        file: stuff.yaml